### ISSUE TITLE
Enable depguard linter and migrate from pkg/errors to standard library

### ISSUE THREAD

**Issue by theyoprst** [nebius/soperator#1001]
## Summary

Enable the `depguard` linter to prevent usage of `github.com/pkg/errors` and complete migration to Go's standard library error handling.

## Context

Part of #680 - Setup linters properly. This addresses dependency management and code quality by enforcing modern Go error handling patterns.

## Tasks Completed

- [x] ✅ **Migration Complete**: Converted ~240+ `errors.Wrap()` calls to `fmt.Errorf()` with `%w` verb
- [x] ✅ **Linter Configuration**: Added `depguard` rule to prevent future `pkg/errors` usage  
- [x] ✅ **Verification**: All tests pass, builds successful

### 1. Code Migration
- Replaced all `errors.Wrap(err, "message")` with `fmt.Errorf("message: %w", err)`
- Removed `github.com/pkg/errors` imports from 38 source files
- Preserved standard library `errors.New()` usage where appropriate
- Cleaned up unused imports

### 2. Linter Configuration
```yaml
linters:
  enable:
    - depguard  # Added to enabled linters

settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use fmt.Errorf() with %w verb instead of pkg/errors for error wrapping"
```

## Benefits Achieved

- 🚀 **Performance**: Standard library error wrapping is more efficient
- 📦 **Dependencies**: Reduced external dependency footprint  
- 🛡️ **Future-proof**: Prevents regression with linter enforcement
- 🎯 **Compatibility**: Better integration with Go 1.13+ error handling

## Verification

```bash
# Test that depguard catches pkg/errors usage
golangci-lint run --enable-only=depguard

# Verify current codebase passes
golangci-lint run ./internal/...
```

## Related

- Addresses part of #680 (Setup linters properly)
- Follows Go best practices for error handling
- Aligns with modern Go development patterns

## Commits

- Migration: 61ef076
- Linter config: e841189
