### ISSUE TITLE
Problem with new values in SlurmConfig

### ISSUE THREAD

**Issue by nandexsp** [nebius/soperator#422]
into the slurm cluster helm, as part of the new deployment with Epilog and Prolog, I set the slurmconfig values as: 
```
slurmConfig:
  epilog: /etc/slurm/scripts/epilog.sh
  prolog: /etc/slurm/scripts/prolog.sh
  defMemPerNode: 1228800
  defCpuPerGPU: 16
  completeWait: 5
  debugFlags: "Cgroup,CPU_Bind,Gres,JobComp,Priority,Script,SelectType,Steps,TraceJobs"
  taskPluginParam: "Verbose"
  maxJobCount: 10000
  minJobAge: 86400
```

Epilog and Prolog are not set in the slurm.conf, neither in the yaml file. There are something that I missed?

Thanks in advance
