### ISSUE TITLE
Add worker features support

### ISSUE THREAD

**Issue by theyoprst** [nebius/soperator#641]
## Problem

Users are unable to configure partitions with a fixed set of nodes:
- They cannot "hard-code" node names in the PartitionConfiguration because soperator manages workers dynamically, which causes controller nodes to fail with the error "Invalid node names in partition <name>"
- They cannot use [Nodesets](https://slurm.schedmd.com/dynamic_nodes.html#partitions) there is no such support in the  soperator yet and soperator lacks support for node features as well

## Proposed Solution

1. Introduce additional settings in the CR + Terraform for feature definitions:
   ```yaml
   worker_features:
   - name: feature1
     hostlist_expr: worker-[0-2,5] # bare name of worker without range is possible too
     nodeset_name: ns_feature1 # if absent or empty, nodeset will not be created
   ```
2. Update `slurmd_entrypoint.sh` to identify which features the current worker belongs to and add them to the `--conf` parameter when invoking slurmd.
3. For each feature create a nodeset (if configured) in the Slurm config like this:
   ```yaml
   Nodeset=ns_feature1 Feature=feature1
   ```
   So the user would be able to configure a custom partition like `PartitionName=$NAME Nodes=ns_feature1 ...`)
